import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout/Header';
import Scaffold from '@/components/layout/Scaffold';
import Footer from '@/components/layout/Footer';
import { ExampleThemeProvider } from '@/context/ExampleThemeProvider';
import StyledComponentsRegistry from '@/utils/registry';
import { dir } from 'i18next';
import i18nConfig from '@/i18nConfig';
import withTranslations from './withTranslations';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// NOTE 정적 페이지 생성
export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

const RootLayout = async ({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) => (
  <html lang={locale} dir={dir(locale)}>
    <body className={inter.className}>
      <StyledComponentsRegistry>
        <ExampleThemeProvider>
          <Scaffold
            header={<Header />}
            body={children}
            footer={<Footer />}
          />
        </ExampleThemeProvider>
      </StyledComponentsRegistry>
    </body>
  </html>
);
export default withTranslations(RootLayout);
