import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout/Header';
import Scaffold from '@/components/layout/Scaffold';
import Footer from '@/components/layout/Footer';
import { ExampleThemeProvider } from '@/context/ExampleThemeProvider';
import StyledComponentsRegistry from '@/lib/registry';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en">
    <body className={inter.className}>
      <StyledComponentsRegistry>
        <ExampleThemeProvider>
          <Scaffold
            header={<Header />}
            body={children}
            footer={<Footer />}
          />
        </ExampleThemeProvider>
      </StyledComponentsRegistry>
    </body>
  </html>
);

export default RootLayout;
