import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import StyledComponentsRegistry from '@/lib/registry';
import Header from '@/components/layout/Header';
import Scaffold from '@/components/layout/Scaffold';
import Footer from '@/components/layout/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en">
    <body className={inter.className}>
      <StyledComponentsRegistry>
        <Scaffold
          header={<Header />}
          body={children}
          footer={<Footer />}
        />
      </StyledComponentsRegistry>
    </body>
  </html>
);

export default RootLayout;
